name: support
description: A collection of extension methods and helper classes for Dart projects.
version: 0.3.0

repository: https://github.com/filipprober/support

environment:
  sdk: ^3.9.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
dependencies:
  pluralize: ^0.0.8

