name: support
description: A Support Package for Dart.
version: 0.2.0

repository: https://github.com/filipprober/support

environment:
  sdk: ^3.9.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

